<a href="https://colab.research.google.com/github/BharathkumarK19/codeAlphaprojects/blob/main/Credit_Score_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Credit score model

In [40]:
#import libraries
import numpy as np
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten

from sklearn.metrics import accuracy_score

In [3]:
import pandas as pd
from zipfile import ZipFile

# Open the zip file
with ZipFile('/content/archive (18).zip') as myzip:
    # Get a list of files in the zip
    file_list = myzip.namelist()

    # Loop through each file
    for file_name in file_list:
        # Check if the file is a CSV
        if file_name.endswith('.csv'):
            # Read the CSV file
            with myzip.open(file_name) as f:
                df = pd.read_csv(f)

            # Now you have the DataFrame 'df' for the current CSV file
            # Do something with the DataFrame (e.g., print it)

In [42]:

x.shape

(1000, 19)

In [5]:
df.columns

Index(['Age', 'Gender', 'Marital Status', 'Education Level',
       'Employment Status', 'Credit Utilization Ratio', 'Payment History',
       'Number of Credit Accounts', 'Loan Amount', 'Interest Rate',
       'Loan Term', 'Type of Loan'],
      dtype='object')

In [6]:
df.head()

,Age,Gender,Marital Status,Education Level,Employment Status,Credit Utilization Ratio,Payment History,Number of Credit Accounts,Loan Amount,Interest Rate,Loan Term,Type of Loan
0,60,Male,Married,Master,Employed,0.22,2685.0,2,4675000,2.65,48,Personal Loan
1,25,Male,Married,High School,Unemployed,0.20,2371.0,9,3619000,5.19,60,Auto Loan
2,30,Female,Single,Master,Employed,0.22,2771.0,6,957000,2.76,12,Auto Loan
3,58,Female,Married,PhD,Unemployed,0.12,1371.0,2,4731000,6.57,60,Auto Loan
4,32,Male,Married,Bachelor,Self-Employed,0.99,828.0,2,3289000,6.28,36,Personal Loan

In [7]:
df=pd.get_dummies(df,columns=['Gender','Marital Status',])

In [8]:
df=pd.get_dummies(df,columns=['Education Level','Employment Status',])

In [9]:
df.head()

,Age,Credit Utilization Ratio,Payment History,Number of Credit Accounts,Loan Amount,Interest Rate,Loan Term,Type of Loan,Gender_Female,Gender_Male,Marital Status_Divorced,Marital Status_Married,Marital Status_Single,Education Level_Bachelor,Education Level_High School,Education Level_Master,Education Level_PhD,Employment Status_Employed,Employment Status_Self-Employed,Employment Status_Unemployed
0,60,0.22,2685.0,2,4675000,2.65,48,Personal Loan,False,True,False,True,False,False,False,True,False,True,False,False
1,25,0.20,2371.0,9,3619000,5.19,60,Auto Loan,False,True,False,True,False,False,True,False,False,False,False,True
2,30,0.22,2771.0,6,957000,2.76,12,Auto Loan,True,False,False,False,True,False,False,True,False,True,False,False
3,58,0.12,1371.0,2,4731000,6.57,60,Auto Loan,True,False,False,True,False,False,False,False,True,False,False,True
4,32,0.99,828.0,2,3289000,6.28,36,Personal Loan,False,True,False,True,False,True,False,False,False,False,True,False

In [10]:
encoder=LabelEncoder()
df['Type of Loan']=encoder.fit_transform(df['Type of Loan'])

In [11]:
df.head()

,Age,Credit Utilization Ratio,Payment History,Number of Credit Accounts,Loan Amount,Interest Rate,Loan Term,Type of Loan,Gender_Female,Gender_Male,Marital Status_Divorced,Marital Status_Married,Marital Status_Single,Education Level_Bachelor,Education Level_High School,Education Level_Master,Education Level_PhD,Employment Status_Employed,Employment Status_Self-Employed,Employment Status_Unemployed
0,60,0.22,2685.0,2,4675000,2.65,48,2,False,True,False,True,False,False,False,True,False,True,False,False
1,25,0.20,2371.0,9,3619000,5.19,60,0,False,True,False,True,False,False,True,False,False,False,False,True
2,30,0.22,2771.0,6,957000,2.76,12,0,True,False,False,False,True,False,False,True,False,True,False,False
3,58,0.12,1371.0,2,4731000,6.57,60,0,True,False,False,True,False,False,False,False,True,False,False,True
4,32,0.99,828.0,2,3289000,6.28,36,2,False,True,False,True,False,True,False,False,False,False,True,False

In [12]:
x=df.drop(columns=['Type of Loan'])
y=df['Type of Loan']

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=4519)

In [14]:
scale=MinMaxScaler()
x_train=scale.fit_transform(x_train)
x_test=scale.transform(x_test)

In [43]:
df['Type of Loan'].value_counts()

Type of Loan
0    348
1    328
2    324
Name: count, dtype: int64

In [117]:
model=Sequential()
model.add(Dense(45,input_shape=(19,)))
model.add(Dense(20,activation='relu'))
model.add(Dense(3,activation='softmax'))

In [118]:
model.summary()

Model: "sequential_20"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_53 (Dense)                     │ (None, 45)                  │             900 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_54 (Dense)                     │ (None, 20)                  │             920 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_55 (Dense)                     │ (None, 3)                   │              63 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,883 (7.36 KB)

 Trainable params: 1,883 (7.36 KB)

 Non-trainable params: 0 (0.00 B)

In [119]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [123]:
history=model.fit(x_train,y_train,epochs=50,validation_split=0.9)

Epoch 1/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6496 - loss: 0.9196 - val_accuracy: 0.4749 - val_loss: 1.0359
Epoch 2/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5921 - loss: 0.9538 - val_accuracy: 0.4822 - val_loss: 1.0379
Epoch 3/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6603 - loss: 0.8795 - val_accuracy: 0.4645 - val_loss: 1.0421
Epoch 4/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6631 - loss: 0.8700 - val_accuracy: 0.4689 - val_loss: 1.0464
Epoch 5/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6699 - loss: 0.8755 - val_accuracy: 0.4704 - val_loss: 1.0505
Epoch 6/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7011 - loss: 0.8426 - val_accuracy: 0.4763 - val_loss: 1.0539
Epoch 7/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6951 - loss: 0.8420 - val_accuracy: 0.4719 - val_loss: 1.0579
Epoch 8/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7253 - loss: 0.8202 - val_accuracy: 0.4675 - val_loss: 1.0617
Epoch 9/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7253 - loss: 0.7986 - val_accuracy: 0.4689 - val_loss: 1.0647
Epoch 10/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7097 - loss: 0.7810 - val_accuracy: 0.4630 - val_loss: 1.0671
Epoch 11/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7310 - loss: 0.7894 - val_accuracy: 0.4630 - val_loss: 1.0702
Epoch 12/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7740 - loss: 0.7531 - val_accuracy: 0.4586 - val_loss: 1.0750
Epoch 13/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7310 - loss: 0.7594 - val_accuracy: 0.4512 - val_loss: 1.0800
Epoch 14/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7466 - loss: 0.7450 - val_accuracy: 0.4571 - val_loss: 1.0847
Epoch 15/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7505 - loss: 0.7282 - val_accuracy: 0.4527 - val_loss: 1.0892
Epoch 16/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7466 - loss: 0.7263 - val_accuracy: 0.4527 - val_loss: 1.0937
Epoch 17/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7534 - loss: 0.7396 - val_accuracy: 0.4512 - val_loss: 1.0996
Epoch 18/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7612 - loss: 0.7359 - val_accuracy: 0.4512 - val_loss: 1.1058
Epoch 19/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7601 - loss: 0.7294 - val_accuracy: 0.4453 - val_loss: 1.1122
Epoch 20/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7836 - loss: 0.6845 - val_accuracy: 0.4423 - val_loss: 1.1193
Epoch 21/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7562 - loss: 0.7197 - val_accuracy: 0.4393 - val_loss: 1.1245
Epoch 22/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7719 - loss: 0.6793 - val_accuracy: 0.4379 - val_loss: 1.1287
Epoch 23/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7640 - loss: 0.6720 - val_accuracy: 0.4334 - val_loss: 1.1324
Epoch 24/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7640 - loss: 0.6830 - val_accuracy: 0.4320 - val_loss: 1.1359
Epoch 25/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7893 - loss: 0.6898 - val_accuracy: 0.4334 - val_loss: 1.1402
Epoch 26/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.8390 - loss: 0.6362 - val_accuracy: 0.4305 - val_loss: 1.1456
Epoch 27/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8184 - loss: 0.6428 - val_accuracy: 0.4246 - val_loss: 1.1519
Epoch 28/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8145 - loss: 0.6525 - val_accuracy: 0.4172 - val_loss: 1.1599
Epoch 29/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7893 - loss: 0.6444 - val_accuracy: 0.4172 - val_loss: 1.1679
Epoch 30/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8223 - loss: 0.6512 - val_accuracy: 0.4201 - val_loss: 1.1739
Epoch 31/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7804 - loss: 0.6584 - val_accuracy: 0.4201 - val_loss: 1.1792
Epoch 32/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8273 - loss: 0.6412 - val_accuracy: 0.4157 - val_loss: 1.1850
Epoch 33/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8184 - loss: 0.6124 - val_accuracy: 0.4172 - val_loss: 1.1905
Epoch 34/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8369 - loss: 0.6213 - val_accuracy: 0.4098 - val_loss: 1.1967
Epoch 35/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8738 - loss: 0.5855 - val_accuracy: 0.4068 - val_loss: 1.2022
Epoch 36/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8699 - loss: 0.6120 - val_accuracy: 0.4038 - val_loss: 1.2073
Epoch 37/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8387 - loss: 0.6210 - val_accuracy: 0.4024 - val_loss: 1.2107
Epoch 38/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8991 - loss: 0.5808 - val_accuracy: 0.3979 - val_loss: 1.2131
Epoch 39/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8952 - loss: 0.5765 - val_accuracy: 0.4024 - val_loss: 1.2146
Epoch 40/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8845 - loss: 0.5770 - val_accuracy: 0.4024 - val_loss: 1.2182
Epoch 41/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8767 - loss: 0.5647 - val_accuracy: 0.3950 - val_loss: 1.2234
Epoch 42/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8874 - loss: 0.5695 - val_accuracy: 0.3905 - val_loss: 1.2288
Epoch 43/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8874 - loss: 0.5776 - val_accuracy: 0.3891 - val_loss: 1.2356
Epoch 44/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8991 - loss: 0.5402 - val_accuracy: 0.3891 - val_loss: 1.2447
Epoch 45/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.8991 - loss: 0.5389 - val_accuracy: 0.3876 - val_loss: 1.2526
Epoch 46/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9097 - loss: 0.5507 - val_accuracy: 0.3905 - val_loss: 1.2585
Epoch 47/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9175 - loss: 0.5211 - val_accuracy: 0.3861 - val_loss: 1.2613
Epoch 48/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8980 - loss: 0.5427 - val_accuracy: 0.3876 - val_loss: 1.2632
Epoch 49/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9204 - loss: 0.5375 - val_accuracy: 0.3891 - val_loss: 1.2646
Epoch 50/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8845 - loss: 0.5242 - val_accuracy: 0.3876 - val_loss: 1.2681